REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1700', '1000', 'LOTS', 'Available inventory', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1701', '1000', 'BREEDING METHOD NAME', 'Breeding method name', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1702', '1000', 'BREEDING METHOD ABBREVIATION', 'Breeding method abbreviation', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1703', '1000', 'BREEDING METHOD NUMBER', 'Breeding method number', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1704', '1000', 'BREEDING METHOD GROUP', 'Breeding method group', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1705', '1000', 'FEMALE PEDIGREE','Pedigree of female parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1706', '1000', 'CROSS-FEMALE PREFERRED NAME', 'Cross-female preferred name', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1707', '1000', 'MALE PEDIGREE','Pedigree of male parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1708', '1000', 'CROSS-MALE PREFERRED NAME', 'Cross-male preferred name', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1709', '1000', 'GERMPLASM DATE', 'Germplasm Date', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1711', '1000', 'PREFERRED ID', 'Preferred ID', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1712', '1000', 'PREFERRED NAME', 'Preferred Name', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1713', '1000', 'TOTAL WITHDRAWALS', 'Seed reservation', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1714', '1000', 'COMMENT', 'Comment on inventory', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1715', '1000', 'LOT_ID', 'LOT Identification', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1716', '1000', 'NEW RES', 'Newly reserved inventory', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1717', '1000', 'RES', 'Reserved inventory', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1718', '1000', 'AVAILABLE', 'Total inventory', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1719', '1000', 'UNITS', 'Inventory units', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1720', '1000', 'LOCATION', 'Lot location', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1721', '1000', 'SCALE', 'Inventory Scale', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1722', '1000', 'AMOUNT', 'Inventory Amount', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1723', '1000', 'FEMALE PARENT', 'Name of Female Parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1724', '1000', 'MALE PARENT', 'Name of Male Parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1725', '1000', 'FGID', 'GID of Female Parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1726', '1000', 'MGID', 'GID of Male Parent', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1727', '1000', 'STOCKID', 'ID of an inventory deposit', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1728', '1000', 'DUPLICATE', 'Duplicate notes', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1729', '1000', 'BULK WITH', 'Stock IDs of stock list for bulking', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1730', '1000', 'BULK COMPL?', 'Is bulking completed?', '0', '0');
-- GROUP ID
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1731', '1000', 'GROUP ID', 'Group ID of a germplasm', '0', '0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `dbxref_id`, `is_obsolete`, `is_relationshiptype`) values('1732','1000','FEMALE PLOT','Female Plot Number',NULL,'0','0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `dbxref_id`, `is_obsolete`, `is_relationshiptype`) values('1733','1000','MALE PLOT','Male Plot Number',NULL,'0','0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `dbxref_id`, `is_obsolete`, `is_relationshiptype`) values('1734','1000','CROSSING DATE','Crossing date',NULL,'0','0');
REPLACE INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `dbxref_id`, `is_obsolete`, `is_relationshiptype`) values('1735','1000','MALE NURSERY','Male Nursery',NULL,'0','0');

INSERT INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1736', '1000', 'STATUS', 'Status of the reserved or committed inventory transactions', '0', '0');
INSERT INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1737', '1000', 'ACTUAL BALANCE', 'Total of all unreserved seed, plus reserved seed that is not yet committed', '0', '0');
INSERT INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1738', '1000', 'RESERVATION', 'Total of single permitted open reservation', '0', '0');
INSERT INTO `cvterm` (`cvterm_id`, `cv_id`, `name`, `definition`, `is_obsolete`, `is_relationshiptype`) VALUES ('1739', '1000', 'LOT STATUS', 'Lot status active (open) or closed', '0', '0');